### ISSUE TITLE
Possible to use with a switch rather than button

### ISSUE THREAD

**Issue by jnowak1054** [Howchoo/pi-power-button#11]
I'm currently using this with a switch rather than a button. I have the switch connected between BCM 3 and ground; if the pi is in a low power state the switch shorting to ground will start the pi, when running (switch is on,) the gpio is pulled low, so when the switch is turned off the pin goes high due to internal pull-up. I have changed in listen-for-shutdown.py:

GPIO.wait_for_edge(3, GPIO.FALLING)
to
GPIO.wait_for_edge(3, GPIO.RISING)

which works great for turning pi on and off. The only issue I have is the pi will boot and stay on with the switch in the off position when power is applied. A quick boot and shutdown is acceptable with the switch in the off position. I was thinking to do a one time check on the pin after the internal pull-up is initialized and perform a shutdown if it is already hi, not 100% sure how to go about this in the cleanest way. Any suggestions.

**Comment by josephtyler** [comment]
Sorry for the major delay here, but this is a really neat idea. I'm going to close this issue, but I'll think about ways to make this optionally work for a switch.
