### ISSUE TITLE
Possible to use other pins?

### ISSUE THREAD

**Issue by janis-ax** [Howchoo/pi-power-button#16]
Is it possible to use another pin rather Pin5 ?

**Comment by ZLevine** [comment]
Unfortunately not for full functionality. There are two main features of the power button here:

1. Shut the Pi down on press (the Pi now consumes zero power)
2. Turn the Pi on (wake the Pi) on press

The wake functionality (#2) requires the SCL pin, pin 5. So if you don't care about turning the Pi back on using the power button, you could use a different GPIO pin for #1 above. Then, to turn the Pi back on, you'd need to disconnect and reconnect the power cord (or use a cord with a physical switch in it).

Note: Of course, for the other connection, you can use any ground pin you want.

I hope this was helpful. Let me know if you have any other questions.

**Comment by seltix5** [comment]
> Unfortunately not for full functionality. There are two main features of the power button here:
> 
> 1. Shut the Pi down on press (the Pi now consumes zero power)
> 2. Turn the Pi on (wake the Pi) on press
> 
> The wake functionality (#2) requires the SCL pin, pin 5. So if you don't care about turning the Pi back on using the power button, you could use a different GPIO pin for #1 above. Then, to turn the Pi back on, you'd need to disconnect and reconnect the power cord (or use a cord with a physical switch in it).
> 
> Note: Of course, for the other connection, you can use any ground pin you want.
> 
> I hope this was helpful. Let me know if you have any other questions.

this info should be on the README.md, thanks !

**Comment by ZLevine** [comment]
@seltix5 thanks for the suggestion—I'll add it now. :)
