### ISSUE TITLE
Program doesn't Activate on boot up. 

### ISSUE THREAD

**Issue by dkingsjr** [Howchoo/pi-power-button#17]
Hello,
I have followed the instructions on your Howchoo article to make this code function... Only problem is, it doesn't start up during the boot. I have to use the command `sudo /etc/init.d/listen-for-shutdown.sh start` in the terminal every time to initialize shutdown if I want to use my button. I'm not sure why this is. I'm using a Raspberry Pi 4B 4gb.

**Comment by ZLevine** [comment]
@dkingsjr sorry I missed this—can you try running through the installation process once more and see if the issue persists?

First, run the uninstall script:

```bash
./pi-power-button/script/uninstall
```

Reboot. Then, reinstall:

```bash
./pi-power-button/script/install
```

Also adding @josephtyler to this as he may have some ideas based on your response.
